### ISSUE TITLE
Error parsing OperationTx for Mint Ops

### ISSUE THREAD

**Issue by federicospini** [ava-labs/avalanchejs#111]
I'm attaching some examples of minting txs from mainnet that fail to parse with two different errors:

# Example n.1

txid: `2B7efoZDxQ9NRpdPixp2NQe2oYGeLQ6yd27C7UXvb2gfb4soJf`
error: __Error: Error - NBytes.fromBuffer: Error: Buffer length must be 20 bytes. Only have 10 remaining in buffer.__
bytes: 
```
11111eqtQvbRXgLu2Ggh1sfXyRxKRFwxiSC283i1LX8fS8uyHtcbbWDxASbh9ktwpg45Hnb5DXR8rHHp9opSTuPZZ1yHpPXP2dm6WDJtjJsmjcSCptEsRemh5jXS8sGNNduHQUj7RP6JUd3kuEpeFFA2jHpuHEDbFddCzhp5MSfTDhWpXXXQnQyAioiPTvoa2Vq53w6KPaTQqkiff11pCV4oR1TZn256p5WQowww2JtUrYm13pKHobfo9AQ3qybD3fzXXQxaDFTXXx4hCAzG4vNzZZSUU2wAnAVpmipxPXGc83pa4rvwBndUFY3JeBcr76jqiQyQoQA3ndM7mRrBUVn5ZTFTDjtT5iMgUCmoxVVDtnY9J6sNi8AZkddnrMsysipGgb6Gmngxc4RrAXvEYEW1uPcYW5DkA2QYuEkgA8RLUghCyLycmnQQeZaL8hAiBbK738nWmyDCy2RWxUuRuCHK1MxGPJQ6vgUUWM2xDb7BcfFgbNu2i3wD6McmKvT5BY4kZa16QyZgA48cJuTeSjZ2fGwDpUjRwGaNEVyEBwdUg9zdq675reoc5nNPd3rycQ9SYqzPdXGzt2vCbUn7L245J6KHGQHG1Pt5otMZr9AgqbWQHonioEKx4UBP1Jkb39wbbBxR2jmLkLuKro6YsWdJvs7JPPbToKnGrPTdHmEJA5L7iB8vLCJyWyuMiD1F7pDXZDVonFP2rss8JLBpcWoAZtXuns85kW5G
```

# Example n.2

txid: `82jDmJsjRtr2PWVVHPP35jmnUfrqQV2rQodBN6njxxdrEAqQt`
error: __Error - NBytes.fromBuffer: Error: Buffer length must be 20 bytes. Only have 10 remaining in buffer.__
bytes: 
```
11111eqtQvbRXgLu2Ggh1sfXyRxKRFwxiSC283i1LX8fS8uyHtcbbWDxASbh9ktwpg45Hnb5DXR8rHHp9opSTuPZZ1yHpPXP2dm6WDJtjJsmjcSCptEsWxuAH1rDiZ6hY3ZQ5AcqJ4Gp2AntfGLUYjtTMNL6icunDzj5pj4dfTD8kW8or3Hr6i9iUu7UadMMATxH59m3ctx6xqY4WToWFLRjn3QKAHA8anbf3o2FDHYLQpxNNpGuWiZB5oiG61KraevHr711zS2Yn6ZNNvnQh6i46f8pNZQRjZCoxGqd9vmaCf2kW1EwYxicfG2Eqwgf95gJaGWgsPV5zAEyjNX7ohLaTMsAdd35GCSavvRT9XYRZj88By4Qmn5o3hTLsSyhjYL8t8E2KyC8uhX2DQ3Vwg2sV7YKyktBCtxmFbyAbWBMdik4fU5gi2XUhiDjQDs1QWGiK6Ao7skknfEEyEvoYEjHYZBjAnXWk6bzTtruEtSPbZMrvKLS7ppKwW9NVthnj39cwBFoyzTEnYCXU68mYYTGatHMVdqWP3VBqq6nALJJ4fFHZ9wUNeE4RQDoT6dRVGTTz7vXmjSsWPgvGagBkjQLpJb9HsiygLsCdirpbtdqdxqgySkMNXWcNKwGhJdG3MEnXDr2QDEo444X1yjebctS3ck6sbSWwrYGZ7Nan8nqTLjkRiCCx1Gugvain72ooe8drXkekS1vqZPsQbX3nFuFv5qG2yRoEZzC
```

# Example n.3

txid :  `2fNEUGLxzs9dJEkwqXEUVKYXy34m82NK3pZuztQpKs5HdrQR5J`
error: __Error: Error - SelectCredentialClass: unknown credid 0__
bytes: 
```
11111eqtQvbRXgLu2Ggh1sfXyRxKRFwxiSC283i1LX8fS8uyHtcbbWDxASbh9ktwpg45Hnb5DXR8rHHp9opSTuPZZ1yHpPXP2dm6WDJtjJsmjcSCptEscH2dUJB1JEw2hTDWjrWZAjTKZiY2RHrJrEcsySqJA1byCMpxekKByTkpHJd8TjGLqEFsf5qmY8LxmAhUi16zoJhXAbLRHgiwTQ9vTxAdL4SUpmTjjnKWdF5Jh59CNfF61KZGzWy7ATxjGLL9RGzy1rQrxLvnL8KxFx8HyShNYrPdoLsRkwVA6htAfN9DaLen2WyGpjCCfMShzAhfqD1bdKshVNncviLEXisCds2dnjLspeTudhBocqA7fsb5bVPHD15Lrvdk3RZsRBBoiFi1MkFxsRFWRDwej4izcj7UUoXE3vUJkev7hgdPoALUDjfgsyTTHei3nSrFbVYhe7MGWBRi8aqsdEurLf9ttQEirfpLbtiK1owbwm8Cs8VuW6Mzj58tJbsh14dqHAMF7zoPuA2GWBcvxczdJTS17RpYMdNbJtwXqxGw9QD4brHwZr1SewAd1nyZwpVquYvSwNMaMbtYuowVXzXaJ9VBR4EBN3skqZLVpomXCFvzw34Ry2RDGHAKa4nRWsY6vTaQ1ZFhUPYQknj82ru4axs8zZyWSCHx5bsvc2Nj9TmaC9Paubwb4b9YFkrhGfwBQHrUybWxMepuSg5GnKQvV8MXVZUTJgEyWb72
```

**Comment by collincusce** [comment]
What are these bytes and where did you get them? When I try to parse them using Tx.fromBuffer() I get different messages.

**Comment by federicospini** [comment]
Examples are `OperationTx`s on X-Chain. Bytes come from [`getTx`](https://docs.avax.network/v1.0/en/api/avm/#avmgettx) API of `avalanchego` and they are CB58-encoded. 

Here follows the whole stacktrace for Example n.1 and n.2:

```
Error: Error - NBytes.fromBuffer: Error: Buffer length must be 20 bytes. Only have 6 remaining in buffer.
    at Address.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/common/nbytes.js:81:19)
    at SECPTransferOutput.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/common/output.js:242:27)
    at SECPTransferOutput.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/common/output.js:404:22)
    at SECPMintOperation.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/ops.js:308:34)
    at TransferableOperation.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/ops.js:202:31)
    at OperationTx.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/operationtx.js:91:25)
    at UnsignedTx.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/tx.js:75:33)
    at Tx.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/tx.js:120:34)
    at main (/home/XXX/parsetx/index.js:28:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Here follows the whole stacktrace for Example n.3:

```
Error: Error - SelectCredentialClass: unknown credid 0
    at Object.exports.SelectCredentialClass (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/credentials.js:35:11)
    at Tx.fromBuffer (/home/XXX/parsetx/node_modules/avalanche/dist/apis/avm/tx.js:127:40)
    at main (/home/XXX/parsetx/index.js:28:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5
```

The issue is that `SECPMintOperation` has a single `TransferOutput` (as reported here https://github.com/ava-labs/avalanchego/blob/master/vms/avm/vm.go#L1053), but here https://github.com/ava-labs/avalanchejs/blob/master/src/apis/avm/ops.ts#L323 a list of `TransferOutput`s is parsed.

**Comment by collincusce** [comment]
Great!! Thanks! I'll work on a patch as my next priority.

**Comment by cgcardona** [comment]
This has been resolved. You can parse the bytes like so

```ts
import { BinTools, Buffer } from "../../src"
import {
  Tx,
} from "../../src/apis/avm"

const bintools: BinTools = BinTools.getInstance()
const bytes: string = "11111eqtQvbRXgLu2Ggh1sfXyRxKRFwxiSC283i1LX8fS8uyHtcbbWDxASbh9ktwpg45Hnb5DXR8rHHp9opSTuPZZ1yHpPXP2dm6WDJtjJsmjcSCptEscH2dUJB1JEw2hTDWjrWZAjTKZiY2RHrJrEcsySqJA1byCMpxekKByTkpHJd8TjGLqEFsf5qmY8LxmAhUi16zoJhXAbLRHgiwTQ9vTxAdL4SUpmTjjnKWdF5Jh59CNfF61KZGzWy7ATxjGLL9RGzy1rQrxLvnL8KxFx8HyShNYrPdoLsRkwVA6htAfN9DaLen2WyGpjCCfMShzAhfqD1bdKshVNncviLEXisCds2dnjLspeTudhBocqA7fsb5bVPHD15Lrvdk3RZsRBBoiFi1MkFxsRFWRDwej4izcj7UUoXE3vUJkev7hgdPoALUDjfgsyTTHei3nSrFbVYhe7MGWBRi8aqsdEurLf9ttQEirfpLbtiK1owbwm8Cs8VuW6Mzj58tJbsh14dqHAMF7zoPuA2GWBcvxczdJTS17RpYMdNbJtwXqxGw9QD4brHwZr1SewAd1nyZwpVquYvSwNMaMbtYuowVXzXaJ9VBR4EBN3skqZLVpomXCFvzw34Ry2RDGHAKa4nRWsY6vTaQ1ZFhUPYQknj82ru4axs8zZyWSCHx5bsvc2Nj9TmaC9Paubwb4b9YFkrhGfwBQHrUybWxMepuSg5GnKQvV8MXVZUTJgEyWb72"
const bytesBuf: Buffer = bintools.cb58Decode(bytes)

const main = async (): Promise<any> => {
  const tx: Tx = new Tx()
  tx.fromBuffer(bytesBuf)
  console.log(tx)
}

main()

```
