### ISSUE TITLE
xchain.getUTXOs => couldn't unmarshal an argument.

### ISSUE THREAD

**Issue by EtienneHelfer** [ava-labs/avalanchejs#211]
hi i have following script which result with error below:

`var fs = require('fs')
var avalancheLib = require('/install2/node_modules/avalanche')
var binTools  = avalancheLib.BinTools.getInstance()
var Avalanche = avalancheLib.Avalanche
var BN 		  = avalancheLib.BN
var Buffer    = avalancheLib.Buffer
var myNetworkID = 1; //default is 3, we want to override that for our local network
var myBlockchainID = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM"; // The X-Chain blockchainID on this network
var avax = new Avalanche("127.0.0.1", 9650, "http", myNetworkID, myBlockchainID);
var xchain = avax.XChain(); //returns a reference to the X-Chain used by AvalancheJS
var myKeychain = xchain.keyChain();
var key = null;
if(fs.existsSync(__dirname + "/privkey")){
	let mypk = Buffer.from(fs.readFileSync(__dirname + "/privkey"), "Base64");
	key = myKeychain.importKey(mypk); 
}else{
	key = myKeychain.makeKey();
	fs.writeFileSync(__dirname + "/privkey", key.privk.toString("Base64"))
}
var myAddresses = myKeychain.getAddresses(); //returns an array of addresses the KeyChain manages
var addressStrings = myKeychain.getAddressStrings(); //returns an array of addresses the KeyChain manages as strings

console.log("MY ADDRESSES",myAddresses)

var prom= xchain.getUTXOs(myAddresses)

prom.catch(function(){
	console.error("CATCH",...arguments)
})
prom.then(function(){
	console.error("THEN",...arguments)
})`

`CATCH Error: couldn't unmarshal an argument. Ensure arguments are valid and properly formatted. See documentation for example calls
    at /install2/node_modules/avalanche/dist/common/jrpcapi.js:74:31
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11754) UnhandledPromiseRejectionWarning: Error: couldn't unmarshal an argument. Ensure arguments are valid and properly formatted. See documentation for example calls
    at /install2/node_modules/avalanche/dist/common/jrpcapi.js:74:31
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

rpc object sent in jrpcapi.js line 65:

{"id":1,"method":"avm.getUTXOs","params":{"addresses":[{"type":"Buffer","data":[42,208,187,83,215,159,58,127,207,203,245,165,40,41,205,2,86,168,65,48]}],"limit":0},"jsonrpc":"2.0"}

Avalanchego version: 

avalanche/1.4.6 [network=mainnet, database=v1.4.5, commit=a13436551d97a33bb9af81bbeebde2eb4573cbe1]

avalanchejs api installed today

**Comment by EtienneHelfer** [comment]
ok worked when passing the address as string and not buffer
