### ISSUE TITLE
examples/info/peers.ts not working

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/avalanchejs#247]
When trying `ts-node examples/info/peers.ts`, I got the following error:

```
/Users/test/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:618
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
examples/info/peers.ts:15:9 - error TS2740: Type 'PeersResponse[]' is missing the following properties from type 'PeersResponse': ip, publicIP, nodeID, version, and 2 more.

15   const peers: PeersResponse = await info.peers([])
           ~~~~~

    at createTSError (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:618:12)
    at reportTSError (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:622:19)
    at getOutput (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:809:36)
    at Object.compile (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yulindong/.nvm/versions/node/v12.14.1/lib/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
```

**Comment by cgcardona** [comment]
Resolved in https://github.com/ava-labs/avalanchejs/pull/251
