### ISSUE TITLE
broken avm example

### ISSUE THREAD

**Issue by paOol** [ava-labs/avalanchejs#312]
`/examples/avm/operationTx-mint-ant.ts`

```
/Users/paool/web/avalanchejs/examples/avm/operationTx-mint-ant.ts:5
  SECPTransferOutput,
                                                         ^
TypeError: amountOutput.getAmount is not a function
    at /Users/paool/web/avalanchejs/examples/avm/operationTx-mint-ant.ts:88:36
    at Array.forEach (<anonymous>)
    at /Users/paool/web/avalanchejs/examples/avm/operationTx-mint-ant.ts:78:9
    at Generator.next (<anonymous>)
    at fulfilled (/Users/paool/web/avalanchejs/examples/avm/operationTx-mint-ant.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by paOol** [comment]
example not broken; just required a build transaction prior.

adding a comment into a separate PR
and closing this issue.
