### ISSUE TITLE
xchain.getTx() fails when trying to return cb58 format

### ISSUE THREAD

**Issue by christroutner** [ava-labs/avalanchejs#623]
AvalancheJS version: 3.15.3 (latest)
Node.js: v16.15.1
npm: 8.13.1
OS: Ubuntu

## Expected Result
I'm expecting `xchain.getTx()` to return a transaction in cb58 format.

## Actual Result
`xchain.getTx()` is throwing an error when trying to retrieve a TX in cb58 format.

## Description
If I'm looking at [the documentation](https://github.com/ava-labs/avalanchejs/blob/1a9393544589522e8995676f871bc631e28062c7/src/apis/avm/api.ts#L945-L966) correctly, `xchain.getTx()` is supposed to return a result in cb58 by default, but instead it returns a hex string.

However, in order to pass the output into `avm.Tx.fromString()` I need it to be in cb58 format. When I manually specify cb58 format, I get this error:

```
Error: couldn't unmarshal an argument. Ensure arguments are valid and properly formatted. See documentation for example calls
    at AVMAPI.<anonymous> (/home/trout/tmp/avax-test/node_modules/avalanche/dist/common/jrpcapi.js:64:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/trout/tmp/avax-test/node_modules/avalanche/dist/common/jrpcapi.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Here is an example script that can reproduce the issue:

```javascript
const Avalanche = require('avalanche')

async function startTest() {
  try {
    const avalanche = new Avalanche.Avalanche('api.avax.network', 443, 'https', 1)
    const avm = avalanche.avm
    const xchain = avalanche.XChain()

    const txid='s2yxU1r5LDN7Q4Yv2UY2JJKaquMt75KyP3breEpqKVhMe4eyt'

    const txString = await xchain.getTx(txid, "cb58")
    console.log('txString: ', txString)

    const tx = avm.Tx()
    tx.fromString(txString)
    console.log('tx: ', tx)
  } catch(err) {
    console.error('Error in test: ', err)
  }
}
startTest()
```

**Comment by yulin-dong** [comment]
See https://docs.avax.network/apis/avalanchego/cb58-deprecation

**Comment by cgcardona** [comment]
Yo Trout! You need to convert the hex returned from `getTx` to a `Buffer` and then encode that `Buffer` as CB58 like so:

```ts
import { Avalanche, BinTools, Buffer } from "avalanche"
import { Tx, AVMAPI } from "avalanche/dist/apis/avm"
const ip: string = "api.avax.network"
const port: number = 443
const protocol: string = "https"
const networkID: number = 1
const bintools: BinTools = BinTools.getInstance()

async function startTest() {
  try {
    const avalanche: Avalanche = new Avalanche(ip, port, protocol, networkID)
    const xchain: AVMAPI = avalanche.XChain()
    const txid: string = 's2yxU1r5LDN7Q4Yv2UY2JJKaquMt75KyP3breEpqKVhMe4eyt'
    const txString: string = await xchain.getTx(txid, "hex") as string
    const buf: Buffer = new Buffer(txString.slice(2), "hex")
    const cb58: string = bintools.cb58Encode(buf)
    console.log('txString: ', txString)

    const tx: Tx = new Tx()
    tx.fromString(cb58)
    console.log('tx: ', tx)
  } catch (err) {
    console.error('Error in test: ', err)
  }
}
startTest()
```

**Comment by christroutner** [comment]
Thanks @cgcardona! That was exactly what I needed. I was getting hung up on the hex to cb58 conversion. I needed your tip to get past it.
